
############# SCRIPT 0 : Fonctions #############

lientyp <- function(i) {
  print(paste(paste0("M02M_LIENTYP_1", " "), sum(base$M02M_LIENTYP_1 == i, na.rm=TRUE)))
  print(paste(paste0("M02M_LIENTYP_2", " "), sum(base$M02M_LIENTYP_2 == i, na.rm=TRUE)))
  print(paste(paste0("M02M_LIENTYP_3", " "), sum(base$M02M_LIENTYP_3 == i, na.rm=TRUE)))
  print(paste(paste0("M02M_LIENTYP_4", " "), sum(base$M02M_LIENTYP_4 == i, na.rm=TRUE)))
  print(paste(paste0("M02M_LIENTYP_5", " "), sum(base$M02M_LIENTYP_5 == i, na.rm=TRUE)))
  print(paste(paste0("M02M_LIENTYP_6", " "), sum(base$M02M_LIENTYP_6 == i, na.rm=TRUE)))
  print(paste(paste0("M02M_LIENTYP_7", " "), sum(base$M02M_LIENTYP_7 == i, na.rm=TRUE)))
  print(paste(paste0("M02M_LIENTYP_8", " "), sum(base$M02M_LIENTYP_8 == i, na.rm=TRUE)))
  print(paste(paste0("M02M_LIENTYP_9", " "), sum(base$M02M_LIENTYP_9 == i, na.rm=TRUE)))
  print(paste(paste0("M02M_LIENTYP_10"), sum(base$M02M_LIENTYP_10 == i, na.rm=TRUE)))
  print(paste(paste0("M02M_LIENTYP_11"), sum(base$M02M_LIENTYP_11 == i, na.rm=TRUE)))
  print(paste(paste0("M02M_LIENTYP_12"), sum(base$M02M_LIENTYP_12 == i, na.rm=TRUE)))
  
  print(paste(paste0("M02P_LIENTYP_1", " "), sum(base$M02P_LIENTYP_1 == i, na.rm=TRUE)))
  print(paste(paste0("M02P_LIENTYP_2", " "), sum(base$M02P_LIENTYP_2 == i, na.rm=TRUE)))
  print(paste(paste0("M02P_LIENTYP_3", " "), sum(base$M02P_LIENTYP_3 == i, na.rm=TRUE)))
  print(paste(paste0("M02P_LIENTYP_4", " "), sum(base$M02P_LIENTYP_4 == i, na.rm=TRUE)))
  print(paste(paste0("M02P_LIENTYP_5", " "), sum(base$M02P_LIENTYP_5 == i, na.rm=TRUE)))
  print(paste(paste0("M02P_LIENTYP_6", " "), sum(base$M02P_LIENTYP_6 == i, na.rm=TRUE)))
  print(paste(paste0("M02P_LIENTYP_7", " "), sum(base$M02P_LIENTYP_7 == i, na.rm=TRUE)))
  print(paste(paste0("M02P_LIENTYP_8", " "), sum(base$M02P_LIENTYP_8 == i, na.rm=TRUE)))
  print(paste(paste0("M02P_LIENTYP_9", " "), sum(base$M02P_LIENTYP_9 == i, na.rm=TRUE)))
  print(paste(paste0("M02P_LIENTYP_10"), sum(base$M02P_LIENTYP_10 == i, na.rm=TRUE)))
  print(paste(paste0("M02P_LIENTYP_11"), sum(base$M02P_LIENTYP_11 == i, na.rm=TRUE)))
  print(paste(paste0("M02P_LIENTYP_12"), sum(base$M02P_LIENTYP_12 == i, na.rm=TRUE)))
  
  print(paste(paste0("A01M_LIENTYP_1", " "), sum(base$A01M_LIENTYP_1 == i, na.rm=TRUE)))
  print(paste(paste0("A01M_LIENTYP_2", " "), sum(base$A01M_LIENTYP_2 == i, na.rm=TRUE)))
  print(paste(paste0("A01M_LIENTYP_3", " "), sum(base$A01M_LIENTYP_3 == i, na.rm=TRUE)))
  print(paste(paste0("A01M_LIENTYP_4", " "), sum(base$A01M_LIENTYP_4 == i, na.rm=TRUE)))
  print(paste(paste0("A01M_LIENTYP_5", " "), sum(base$A01M_LIENTYP_5 == i, na.rm=TRUE)))
  print(paste(paste0("A01M_LIENTYP_6", " "), sum(base$A01M_LIENTYP_6 == i, na.rm=TRUE)))
  print(paste(paste0("A01M_LIENTYP_7", " "), sum(base$A01M_LIENTYP_7 == i, na.rm=TRUE)))
  print(paste(paste0("A01M_LIENTYP_8", " "), sum(base$A01M_LIENTYP_8 == i, na.rm=TRUE)))
  print(paste(paste0("A01M_LIENTYP_9", " "), sum(base$A01M_LIENTYP_9 == i, na.rm=TRUE)))
  print(paste(paste0("A01M_LIENTYP_10"), sum(base$A01M_LIENTYP_10 == i, na.rm=TRUE)))
  print(paste(paste0("A01M_LIENTYP_11"), sum(base$A01M_LIENTYP_11 == i, na.rm=TRUE)))
  print(paste(paste0("A01M_LIENTYP_12"), sum(base$A01M_LIENTYP_12 == i, na.rm=TRUE)))
  print(paste(paste0("A01M_LIENTYP_13"), sum(base$A01M_LIENTYP_13 == i, na.rm=TRUE)))
  
  print(paste(paste0("A01P_LIENTYP_1", " "), sum(base$A01P_LIENTYP_1 == i, na.rm=TRUE)))
  print(paste(paste0("A01P_LIENTYP_2", " "), sum(base$A01P_LIENTYP_2 == i, na.rm=TRUE)))
  print(paste(paste0("A01P_LIENTYP_3", " "), sum(base$A01P_LIENTYP_3 == i, na.rm=TRUE)))
  print(paste(paste0("A01P_LIENTYP_4", " "), sum(base$A01P_LIENTYP_4 == i, na.rm=TRUE)))
  print(paste(paste0("A01P_LIENTYP_5", " "), sum(base$A01P_LIENTYP_5 == i, na.rm=TRUE)))
  print(paste(paste0("A01P_LIENTYP_6", " "), sum(base$A01P_LIENTYP_6 == i, na.rm=TRUE)))
  print(paste(paste0("A01P_LIENTYP_7", " "), sum(base$A01P_LIENTYP_7 == i, na.rm=TRUE)))
  print(paste(paste0("A01P_LIENTYP_8", " "), sum(base$A01P_LIENTYP_8 == i, na.rm=TRUE)))
  print(paste(paste0("A01P_LIENTYP_9", " "), sum(base$A01P_LIENTYP_9 == i, na.rm=TRUE)))
  print(paste(paste0("A01P_LIENTYP_10"), sum(base$A01P_LIENTYP_10 == i, na.rm=TRUE)))
  print(paste(paste0("A01P_LIENTYP_11"), sum(base$A01P_LIENTYP_11 == i, na.rm=TRUE)))
  print(paste(paste0("A01P_LIENTYP_12"), sum(base$A01P_LIENTYP_12 == i, na.rm=TRUE)))
  
  print(paste(paste0("A02M_LIENTYP_1", " "), sum(base$A02M_LIENTYP_1 == i, na.rm=TRUE)))
  print(paste(paste0("A02M_LIENTYP_2", " "), sum(base$A02M_LIENTYP_2 == i, na.rm=TRUE)))
  print(paste(paste0("A02M_LIENTYP_3", " "), sum(base$A02M_LIENTYP_3 == i, na.rm=TRUE)))
  print(paste(paste0("A02M_LIENTYP_4", " "), sum(base$A02M_LIENTYP_4 == i, na.rm=TRUE)))
  print(paste(paste0("A02M_LIENTYP_5", " "), sum(base$A02M_LIENTYP_5 == i, na.rm=TRUE)))
  print(paste(paste0("A02M_LIENTYP_6", " "), sum(base$A02M_LIENTYP_6 == i, na.rm=TRUE)))
  print(paste(paste0("A02M_LIENTYP_7", " "), sum(base$A02M_LIENTYP_7 == i, na.rm=TRUE)))
  print(paste(paste0("A02M_LIENTYP_8", " "), sum(base$A02M_LIENTYP_8 == i, na.rm=TRUE)))
  print(paste(paste0("A02M_LIENTYP_9", " "), sum(base$A02M_LIENTYP_9 == i, na.rm=TRUE)))
  print(paste(paste0("A02M_LIENTYP_10"), sum(base$A02M_LIENTYP_10 == i, na.rm=TRUE)))
  print(paste(paste0("A02M_LIENTYP_11"), sum(base$A02M_LIENTYP_11 == i, na.rm=TRUE)))
  print(paste(paste0("A02M_LIENTYP_12"), sum(base$A02M_LIENTYP_12 == i, na.rm=TRUE)))
  print(paste(paste0("A02M_LIENTYP_13"), sum(base$A02M_LIENTYP_13 == i, na.rm=TRUE)))
  print(paste(paste0("A02M_LIENTYP_14"), sum(base$A02M_LIENTYP_14 == i, na.rm=TRUE)))
  print(paste(paste0("A02M_LIENTYP_15"), sum(base$A02M_LIENTYP_15 == i, na.rm=TRUE)))
  print(paste(paste0("A02M_LIENTYP_16"), sum(base$A02M_LIENTYP_16 == i, na.rm=TRUE)))
  
  print(paste(paste0("A02P_LIENTYP_1", " "), sum(base$A02P_LIENTYP_1 == i, na.rm=TRUE)))
  print(paste(paste0("A02P_LIENTYP_2", " "), sum(base$A02P_LIENTYP_2 == i, na.rm=TRUE)))
  print(paste(paste0("A02P_LIENTYP_3", " "), sum(base$A02P_LIENTYP_3 == i, na.rm=TRUE)))
  print(paste(paste0("A02P_LIENTYP_4", " "), sum(base$A02P_LIENTYP_4 == i, na.rm=TRUE)))
  print(paste(paste0("A02P_LIENTYP_5", " "), sum(base$A02P_LIENTYP_5 == i, na.rm=TRUE)))
  print(paste(paste0("A02P_LIENTYP_6", " "), sum(base$A02P_LIENTYP_6 == i, na.rm=TRUE)))
  print(paste(paste0("A02P_LIENTYP_7", " "), sum(base$A02P_LIENTYP_7 == i, na.rm=TRUE)))
  print(paste(paste0("A02P_LIENTYP_8", " "), sum(base$A02P_LIENTYP_8 == i, na.rm=TRUE)))
  print(paste(paste0("A02P_LIENTYP_9", " "), sum(base$A02P_LIENTYP_9 == i, na.rm=TRUE)))
  print(paste(paste0("A02P_LIENTYP_10"), sum(base$A02P_LIENTYP_10 == i, na.rm=TRUE)))
  print(paste(paste0("A02P_LIENTYP_11"), sum(base$A02P_LIENTYP_11 == i, na.rm=TRUE)))
  print(paste(paste0("A02P_LIENTYP_12"), sum(base$A02P_LIENTYP_12 == i, na.rm=TRUE)))
  print(paste(paste0("A02P_LIENTYP_13"), sum(base$A02P_LIENTYP_13 == i, na.rm=TRUE)))
  print(paste(paste0("A02P_LIENTYP_14"), sum(base$A02P_LIENTYP_14 == i, na.rm=TRUE)))
  print(paste(paste0("A02P_LIENTYP_15"), sum(base$A02P_LIENTYP_15 == i, na.rm=TRUE)))
  print(paste(paste0("A02P_LIENTYP_16"), sum(base$A02P_LIENTYP_16 == i, na.rm=TRUE)))
  
  print(paste(paste0("A03R_LIENTYP_1", " "), sum(base$A03R_LIENTYP_1 == i, na.rm=TRUE)))
  print(paste(paste0("A03R_LIENTYP_2", " "), sum(base$A03R_LIENTYP_2 == i, na.rm=TRUE)))
  print(paste(paste0("A03R_LIENTYP_3", " "), sum(base$A03R_LIENTYP_3 == i, na.rm=TRUE)))
  print(paste(paste0("A03R_LIENTYP_4", " "), sum(base$A03R_LIENTYP_4 == i, na.rm=TRUE)))
  print(paste(paste0("A03R_LIENTYP_5", " "), sum(base$A03R_LIENTYP_5 == i, na.rm=TRUE)))
  print(paste(paste0("A03R_LIENTYP_6", " "), sum(base$A03R_LIENTYP_6 == i, na.rm=TRUE)))
  print(paste(paste0("A03R_LIENTYP_7", " "), sum(base$A03R_LIENTYP_7 == i, na.rm=TRUE)))
  print(paste(paste0("A03R_LIENTYP_8", " "), sum(base$A03R_LIENTYP_8 == i, na.rm=TRUE)))
  print(paste(paste0("A03R_LIENTYP_9", " "), sum(base$A03R_LIENTYP_9 == i, na.rm=TRUE)))
  print(paste(paste0("A03R_LIENTYP_10"), sum(base$A03R_LIENTYP_10 == i, na.rm=TRUE)))
  print(paste(paste0("A03R_LIENTYP_11"), sum(base$A03R_LIENTYP_11 == i, na.rm=TRUE)))
  print(paste(paste0("A03R_LIENTYP_12"), sum(base$A03R_LIENTYP_12 == i, na.rm=TRUE)))
  print(paste(paste0("A03R_LIENTYP_13"), sum(base$A03R_LIENTYP_13 == i, na.rm=TRUE)))
  print(paste(paste0("A03R_LIENTYP_14"), sum(base$A03R_LIENTYP_14 == i, na.rm=TRUE)))
  print(paste(paste0("A03R_LIENTYP_15"), sum(base$A03R_LIENTYP_15 == i, na.rm=TRUE)))
  print(paste(paste0("A03R_LIENTYP_16"), sum(base$A03R_LIENTYP_16 == i, na.rm=TRUE)))
  print(paste(paste0("A03R_LIENTYP_17"), sum(base$A03R_LIENTYP_17 == i, na.rm=TRUE)))
  print(paste(paste0("A03R_LIENTYP_18"), sum(base$A03R_LIENTYP_18 == i, na.rm=TRUE)))
}

condlientyp <- function(i, j) {
  print(paste(paste0("M02M_LIENTYP_4", " "), sum(base$M02M_LIENTYP_4 == i & base$M02M_SEXEC1_4 == j, na.rm=TRUE)))
  print(paste(paste0("M02M_LIENTYP_5", " "), sum(base$M02M_LIENTYP_5 == i & base$M02M_SEXEC1_5 == j, na.rm=TRUE)))
  print(paste(paste0("M02M_LIENTYP_6", " "), sum(base$M02M_LIENTYP_6 == i & base$M02M_SEXEC1_6 == j, na.rm=TRUE)))
  print(paste(paste0("M02M_LIENTYP_7", " "), sum(base$M02M_LIENTYP_7 == i & base$M02M_SEXEC1_7 == j, na.rm=TRUE)))
  print(paste(paste0("M02M_LIENTYP_8", " "), sum(base$M02M_LIENTYP_8 == i & base$M02M_SEXEC1_8 == j, na.rm=TRUE)))
  print(paste(paste0("M02M_LIENTYP_9", " "), sum(base$M02M_LIENTYP_9 == i & base$M02M_SEXEC1_9 == j, na.rm=TRUE)))
  print(paste(paste0("M02M_LIENTYP_10"), sum(base$M02M_LIENTYP_10 == i & base$M02M_SEXEC1_10 == j, na.rm=TRUE)))
  print(paste(paste0("M02M_LIENTYP_11"), sum(base$M02M_LIENTYP_11 == i & base$M02M_SEXEC1_11 == j, na.rm=TRUE)))
  print(paste(paste0("M02M_LIENTYP_12"), sum(base$M02M_LIENTYP_12 == i & base$M02M_SEXEC1_12 == j, na.rm=TRUE)))
  
  print(paste(paste0("M02P_LIENTYP_4", " "), sum(base$M02P_LIENTYP_4 == i & base$M02P_SEXEC2_4 == j, na.rm=TRUE)))
  print(paste(paste0("M02P_LIENTYP_5", " "), sum(base$M02P_LIENTYP_5 == i & base$M02P_SEXEC2_5 == j, na.rm=TRUE)))
  print(paste(paste0("M02P_LIENTYP_6", " "), sum(base$M02P_LIENTYP_6 == i & base$M02P_SEXEC2_6 == j, na.rm=TRUE)))
  print(paste(paste0("M02P_LIENTYP_7", " "), sum(base$M02P_LIENTYP_7 == i & base$M02P_SEXEC2_7 == j, na.rm=TRUE)))
  print(paste(paste0("M02P_LIENTYP_8", " "), sum(base$M02P_LIENTYP_8 == i & base$M02P_SEXEC2_8 == j, na.rm=TRUE)))
  print(paste(paste0("M02P_LIENTYP_9", " "), sum(base$M02P_LIENTYP_9 == i & base$M02P_SEXEC2_9 == j, na.rm=TRUE)))
  print(paste(paste0("M02P_LIENTYP_10"), sum(base$M02P_LIENTYP_10 == i & base$M02P_SEXEC2_10 == j, na.rm=TRUE)))
  print(paste(paste0("M02P_LIENTYP_11"), sum(base$M02P_LIENTYP_11 == i & base$M02P_SEXEC2_11 == j, na.rm=TRUE)))
  print(paste(paste0("M02P_LIENTYP_12"), sum(base$M02P_LIENTYP_12 == i & base$M02P_SEXEC2_12 == j, na.rm=TRUE)))
  
  print(paste(paste0("A01M_LIENTYP_4", " "), sum(base$A01M_LIENTYP_4 == i & base$A01M_SEXE_4 == j, na.rm=TRUE)))
  print(paste(paste0("A01M_LIENTYP_5", " "), sum(base$A01M_LIENTYP_5 == i & base$A01M_SEXE_5 == j, na.rm=TRUE)))
  print(paste(paste0("A01M_LIENTYP_6", " "), sum(base$A01M_LIENTYP_6 == i & base$A01M_SEXE_6 == j, na.rm=TRUE)))
  print(paste(paste0("A01M_LIENTYP_7", " "), sum(base$A01M_LIENTYP_7 == i & base$A01M_SEXE_7 == j, na.rm=TRUE)))
  print(paste(paste0("A01M_LIENTYP_8", " "), sum(base$A01M_LIENTYP_8 == i & base$A01M_SEXE_8 == j, na.rm=TRUE)))
  print(paste(paste0("A01M_LIENTYP_9", " "), sum(base$A01M_LIENTYP_9 == i & base$A01M_SEXE_9 == j, na.rm=TRUE)))
  print(paste(paste0("A01M_LIENTYP_10"), sum(base$A01M_LIENTYP_10 == i & base$A01M_SEXE_10 == j, na.rm=TRUE)))
  print(paste(paste0("A01M_LIENTYP_11"), sum(base$A01M_LIENTYP_11 == i & base$A01M_SEXE_11 == j, na.rm=TRUE)))
  print(paste(paste0("A01M_LIENTYP_12"), sum(base$A01M_LIENTYP_12 == i & base$A01M_SEXE_12 == j, na.rm=TRUE)))
  print(paste(paste0("A01M_LIENTYP_13"), sum(base$A01M_LIENTYP_13 == i & base$A01M_SEXE_13 == j, na.rm=TRUE)))
  
  print(paste(paste0("A01P_LIENTYP_4", " "), sum(base$A01P_LIENTYP_4 == i & base$A01P_SEXE_4 == j, na.rm=TRUE)))
  print(paste(paste0("A01P_LIENTYP_5", " "), sum(base$A01P_LIENTYP_5 == i & base$A01P_SEXE_5 == j, na.rm=TRUE)))
  print(paste(paste0("A01P_LIENTYP_6", " "), sum(base$A01P_LIENTYP_6 == i & base$A01P_SEXE_6 == j, na.rm=TRUE)))
  print(paste(paste0("A01P_LIENTYP_7", " "), sum(base$A01P_LIENTYP_7 == i & base$A01P_SEXE_7 == j, na.rm=TRUE)))
  print(paste(paste0("A01P_LIENTYP_8", " "), sum(base$A01P_LIENTYP_8 == i & base$A01P_SEXE_8 == j, na.rm=TRUE)))
  print(paste(paste0("A01P_LIENTYP_9", " "), sum(base$A01P_LIENTYP_9 == i & base$A01P_SEXE_9 == j, na.rm=TRUE)))
  print(paste(paste0("A01P_LIENTYP_10"), sum(base$A01P_LIENTYP_10 == i & base$A01P_SEXE_10 == j, na.rm=TRUE)))
  print(paste(paste0("A01P_LIENTYP_11"), sum(base$A01P_LIENTYP_11 == i & base$A01P_SEXE_11 == j, na.rm=TRUE)))
  print(paste(paste0("A01P_LIENTYP_12"), sum(base$A01P_LIENTYP_12 == i & base$A01P_SEXE_12 == j, na.rm=TRUE)))
  
  print(paste(paste0("A02M_LIENTYP_4", " "), sum(base$A02M_LIENTYP_4 == i & base$A02M_SEXE_4 == j, na.rm=TRUE)))
  print(paste(paste0("A02M_LIENTYP_5", " "), sum(base$A02M_LIENTYP_5 == i & base$A02M_SEXE_5 == j, na.rm=TRUE)))
  print(paste(paste0("A02M_LIENTYP_6", " "), sum(base$A02M_LIENTYP_6 == i & base$A02M_SEXE_6 == j, na.rm=TRUE)))
  print(paste(paste0("A02M_LIENTYP_7", " "), sum(base$A02M_LIENTYP_7 == i & base$A02M_SEXE_7 == j, na.rm=TRUE)))
  print(paste(paste0("A02M_LIENTYP_8", " "), sum(base$A02M_LIENTYP_8 == i & base$A02M_SEXE_8 == j, na.rm=TRUE)))
  print(paste(paste0("A02M_LIENTYP_9", " "), sum(base$A02M_LIENTYP_9 == i & base$A02M_SEXE_9 == j, na.rm=TRUE)))
  print(paste(paste0("A02M_LIENTYP_10"), sum(base$A02M_LIENTYP_10 == i & base$A02M_SEXE_10 == j, na.rm=TRUE)))
  print(paste(paste0("A02M_LIENTYP_11"), sum(base$A02M_LIENTYP_11 == i & base$A02M_SEXE_11 == j, na.rm=TRUE)))
  print(paste(paste0("A02M_LIENTYP_12"), sum(base$A02M_LIENTYP_12 == i & base$A02M_SEXE_12 == j, na.rm=TRUE)))
  print(paste(paste0("A02M_LIENTYP_13"), sum(base$A02M_LIENTYP_13 == i & base$A02M_SEXE_13 == j, na.rm=TRUE)))
  print(paste(paste0("A02M_LIENTYP_14"), sum(base$A02M_LIENTYP_14 == i & base$A02M_SEXE_14 == j, na.rm=TRUE)))
  print(paste(paste0("A02M_LIENTYP_15"), sum(base$A02M_LIENTYP_15 == i & base$A02M_SEXE_15 == j, na.rm=TRUE)))
  print(paste(paste0("A02M_LIENTYP_16"), sum(base$A02M_LIENTYP_16 == i & base$A02M_SEXE_16 == j, na.rm=TRUE)))
  
  print(paste(paste0("A02P_LIENTYP_4", " "), sum(base$A02P_LIENTYP_4 == i & base$A02P_SEXE_4 == j, na.rm=TRUE)))
  print(paste(paste0("A02P_LIENTYP_5", " "), sum(base$A02P_LIENTYP_5 == i & base$A02P_SEXE_5 == j, na.rm=TRUE)))
  print(paste(paste0("A02P_LIENTYP_6", " "), sum(base$A02P_LIENTYP_6 == i & base$A02P_SEXE_6 == j, na.rm=TRUE)))
  print(paste(paste0("A02P_LIENTYP_7", " "), sum(base$A02P_LIENTYP_7 == i & base$A02P_SEXE_7 == j, na.rm=TRUE)))
  print(paste(paste0("A02P_LIENTYP_8", " "), sum(base$A02P_LIENTYP_8 == i & base$A02P_SEXE_8 == j, na.rm=TRUE)))
  print(paste(paste0("A02P_LIENTYP_9", " "), sum(base$A02P_LIENTYP_9 == i & base$A02P_SEXE_9 == j, na.rm=TRUE)))
  print(paste(paste0("A02P_LIENTYP_10"), sum(base$A02P_LIENTYP_10 == i & base$A02P_SEXE_10 == j, na.rm=TRUE)))
  print(paste(paste0("A02P_LIENTYP_11"), sum(base$A02P_LIENTYP_11 == i & base$A02P_SEXE_11 == j, na.rm=TRUE)))
  print(paste(paste0("A02P_LIENTYP_12"), sum(base$A02P_LIENTYP_12 == i & base$A02P_SEXE_12 == j, na.rm=TRUE)))
  print(paste(paste0("A02P_LIENTYP_13"), sum(base$A02P_LIENTYP_13 == i & base$A02P_SEXE_13 == j, na.rm=TRUE)))
  print(paste(paste0("A02P_LIENTYP_14"), sum(base$A02P_LIENTYP_14 == i & base$A02P_SEXE_14 == j, na.rm=TRUE)))
  print(paste(paste0("A02P_LIENTYP_15"), sum(base$A02P_LIENTYP_15 == i & base$A02P_SEXE_15 == j, na.rm=TRUE)))
  print(paste(paste0("A02P_LIENTYP_16"), sum(base$A02P_LIENTYP_16 == i & base$A02P_SEXE_16 == j, na.rm=TRUE)))
  
  print(paste(paste0("A03R_LIENTYP_4", " "), sum(base$A03R_LIENTYP_4 == i & base$A03R_SEXE_4 == j, na.rm=TRUE)))
  print(paste(paste0("A03R_LIENTYP_5", " "), sum(base$A03R_LIENTYP_5 == i & base$A03R_SEXE_5 == j, na.rm=TRUE)))
  print(paste(paste0("A03R_LIENTYP_6", " "), sum(base$A03R_LIENTYP_6 == i & base$A03R_SEXE_6 == j, na.rm=TRUE)))
  print(paste(paste0("A03R_LIENTYP_7", " "), sum(base$A03R_LIENTYP_7 == i & base$A03R_SEXE_7 == j, na.rm=TRUE)))
  print(paste(paste0("A03R_LIENTYP_8", " "), sum(base$A03R_LIENTYP_8 == i & base$A03R_SEXE_8 == j, na.rm=TRUE)))
  print(paste(paste0("A03R_LIENTYP_9", " "), sum(base$A03R_LIENTYP_9 == i & base$A03R_SEXE_9 == j, na.rm=TRUE)))
  print(paste(paste0("A03R_LIENTYP_10"), sum(base$A03R_LIENTYP_10 == i & base$A03R_SEXE_10 == j, na.rm=TRUE)))
  print(paste(paste0("A03R_LIENTYP_11"), sum(base$A03R_LIENTYP_11 == i & base$A03R_SEXE_11 == j, na.rm=TRUE)))
  print(paste(paste0("A03R_LIENTYP_12"), sum(base$A03R_LIENTYP_12 == i & base$A03R_SEXE_12 == j, na.rm=TRUE)))
  print(paste(paste0("A03R_LIENTYP_13"), sum(base$A03R_LIENTYP_13 == i & base$A03R_SEXE_13 == j, na.rm=TRUE)))
  print(paste(paste0("A03R_LIENTYP_14"), sum(base$A03R_LIENTYP_14 == i & base$A03R_SEXE_14 == j, na.rm=TRUE)))
  print(paste(paste0("A03R_LIENTYP_15"), sum(base$A03R_LIENTYP_15 == i & base$A03R_SEXE_15 == j, na.rm=TRUE)))
  print(paste(paste0("A03R_LIENTYP_16"), sum(base$A03R_LIENTYP_16 == i & base$A03R_SEXE_16 == j, na.rm=TRUE)))
  print(paste(paste0("A03R_LIENTYP_17"), sum(base$A03R_LIENTYP_17 == i & base$A03R_SEXE_17 == j, na.rm=TRUE)))
  print(paste(paste0("A03R_LIENTYP_18"), sum(base$A03R_LIENTYP_18 == i & base$A03R_SEXE_18 == j, na.rm=TRUE)))
}

sexe_labeller <- function(variable,value){
  return(sexe_names[value])
}

get_only_legend <- function(plot) {
  plot_table <- ggplot_gtable(ggplot_build(plot))
  legend_plot <- which(sapply(plot_table$grobs, function(x) x$name) == "guide-box")
  legend <- plot_table$grobs[[legend_plot]]
  return(legend)
}

combine <- function(mothervar, fathervar, combvar) {
  base[, (combvar) := get(mothervar)]
  base[is.na(get(combvar)) & !is.na(get(fathervar)),
       (combvar) := get(fathervar)]
  return(base)
}


